SOTO = SOTO or {}
SOTO.CharacterTrait = {}
SOTO.CharacterProfession = {}

-- =====================
-- CHARACTER TRAITS
-- =====================

SOTO.CharacterTrait.TAUT = CharacterTrait.register("soto:taut")
SOTO.CharacterTrait.SLACK = CharacterTrait.register("soto:slack")
SOTO.CharacterTrait.FAST_METABOLISM = CharacterTrait.register("soto:fastmetabolism")
SOTO.CharacterTrait.SLOW_METABOLISM = CharacterTrait.register("soto:slowmetabolism")
SOTO.CharacterTrait.SNEAKY = CharacterTrait.register("soto:sneaky")
SOTO.CharacterTrait.LIGHTFOOTED = CharacterTrait.register("soto:lightfooted")
SOTO.CharacterTrait.AGILE = CharacterTrait.register("soto:agile")
SOTO.CharacterTrait.GYMNAST2 = CharacterTrait.register("soto:gymnast2")
SOTO.CharacterTrait.GARDENER2 = CharacterTrait.register("soto:gardener2")
SOTO.CharacterTrait.FORAGER = CharacterTrait.register("soto:forager")
SOTO.CharacterTrait.TRAPPER = CharacterTrait.register("soto:trapper")
SOTO.CharacterTrait.TRACKER = CharacterTrait.register("soto:tracker")
SOTO.CharacterTrait.MUSHROOM_PICKER = CharacterTrait.register("soto:mushroompicker")
SOTO.CharacterTrait.ENTOMOLOGIST = CharacterTrait.register("soto:entomologist")
SOTO.CharacterTrait.IMPROVED_FORAGING = CharacterTrait.register("soto:improvedforaging")
SOTO.CharacterTrait.ADVANCED_FORAGING = CharacterTrait.register("soto:advancedforaging")
SOTO.CharacterTrait.INVENTIVE2 = CharacterTrait.register("soto:inventive2")
SOTO.CharacterTrait.FIRST_AID2 = CharacterTrait.register("soto:firstaid2")
SOTO.CharacterTrait.CULINARY = CharacterTrait.register("soto:culinary")
SOTO.CharacterTrait.HANDY2 = CharacterTrait.register("soto:handy2")
SOTO.CharacterTrait.WOODWORKER = CharacterTrait.register("soto:woodworker")
SOTO.CharacterTrait.ELECTRICALMECHANIC = CharacterTrait.register("soto:electricalmechanic")
SOTO.CharacterTrait.AUTOMECHANIC = CharacterTrait.register("soto:automechanic")
SOTO.CharacterTrait.METAL_WELDER = CharacterTrait.register("soto:metalwelder")
SOTO.CharacterTrait.MASONRY = CharacterTrait.register("soto:masonry")
SOTO.CharacterTrait.POTTER = CharacterTrait.register("soto:potter")
SOTO.CharacterTrait.GLASSBLOWER = CharacterTrait.register("soto:glassblower")
SOTO.CharacterTrait.KNAPPING_BASICS = CharacterTrait.register("soto:knappingbasics")
SOTO.CharacterTrait.ANIMAL_FRIEND = CharacterTrait.register("soto:animalfriend")
SOTO.CharacterTrait.ANIMAL_FRIEND2 = CharacterTrait.register("soto:animalfriend2")
SOTO.CharacterTrait.SLAUGHTERER = CharacterTrait.register("soto:slaughterer")
SOTO.CharacterTrait.SLAUGHTERER2 = CharacterTrait.register("soto:slaughterer2")
SOTO.CharacterTrait.KNIFER = CharacterTrait.register("soto:knifer")
SOTO.CharacterTrait.BLUDGEONER = CharacterTrait.register("soto:bludgeoner")
SOTO.CharacterTrait.CUTTER = CharacterTrait.register("soto:cutter")
SOTO.CharacterTrait.SPEARMAN = CharacterTrait.register("soto:spearman")
SOTO.CharacterTrait.SWORDSMAN = CharacterTrait.register("soto:swordsman")
SOTO.CharacterTrait.DURABILITY = CharacterTrait.register("soto:durability")
SOTO.CharacterTrait.SHOOTER = CharacterTrait.register("soto:shooter")
SOTO.CharacterTrait.SHOOTER2 = CharacterTrait.register("soto:shooter2")
SOTO.CharacterTrait.EXP_SHOOTER = CharacterTrait.register("soto:expshooter")
SOTO.CharacterTrait.HUNTER2 = CharacterTrait.register("soto:hunter2")
SOTO.CharacterTrait.SCOUT2 = CharacterTrait.register("soto:formerscout2")
SOTO.CharacterTrait.HERBALIST2 = CharacterTrait.register("soto:herbalist2")
SOTO.CharacterTrait.GENERATOR_EXPERT = CharacterTrait.register("soto:generatorexpert")
SOTO.CharacterTrait.GENERATOR_EXPERT2 = CharacterTrait.register("soto:generatorexpert2")
SOTO.CharacterTrait.CALMMINDED = CharacterTrait.register("soto:calmminded")
SOTO.CharacterTrait.MARATHON_RUNNER = CharacterTrait.register("soto:marathonrunner")
--SOTO.CharacterTrait.NINJAWAY = CharacterTrait.register("soto:ninjaway")
--SOTO.CharacterTrait.NINJAWAY2 = CharacterTrait.register("soto:ninjaway2")
SOTO.CharacterTrait.BREATHING_TECHNIQUE = CharacterTrait.register("soto:breathingtechnique")
SOTO.CharacterTrait.BREATHING_TECHNIQUE2 = CharacterTrait.register("soto:breathingtechnique2")
SOTO.CharacterTrait.TIRELESS = CharacterTrait.register("soto:tireless")
SOTO.CharacterTrait.TIRELESS2 = CharacterTrait.register("soto:tireless2")
SOTO.CharacterTrait.STRONG_GRIP = CharacterTrait.register("soto:stronggrip")
SOTO.CharacterTrait.STRONG_GRIP2 = CharacterTrait.register("soto:stronggrip2")
SOTO.CharacterTrait.SPEED_DEMON2 = CharacterTrait.register("soto:speeddemon2")
SOTO.CharacterTrait.EAGLE_EYED2 = CharacterTrait.register("soto:eagleeyed2")
SOTO.CharacterTrait.NIGHT_VISION2 = CharacterTrait.register("soto:nightvision2")
SOTO.CharacterTrait.KEEN_HEARING2 = CharacterTrait.register("soto:keenhearing2")
SOTO.CharacterTrait.INCONSPICUOUS2 = CharacterTrait.register("soto:inconspicuous2")
SOTO.CharacterTrait.ADRENALINE_JUNKIE2 = CharacterTrait.register("soto:adrenalinejunkie2")
SOTO.CharacterTrait.BRAVE2 = CharacterTrait.register("soto:brave2")
SOTO.CharacterTrait.DESENSITIZED2 = CharacterTrait.register("soto:desensitized2")
SOTO.CharacterTrait.GRACEFUL2 = CharacterTrait.register("soto:graceful2")
SOTO.CharacterTrait.FAST_READER2 = CharacterTrait.register("soto:fastreader2")
SOTO.CharacterTrait.FEAR_OF_THE_DARK = CharacterTrait.register("soto:fearofthedark")
SOTO.CharacterTrait.OUTDOORSMAN2 = CharacterTrait.register("soto:outdoorsman2")
SOTO.CharacterTrait.CRUELTY = CharacterTrait.register("soto:cruelty")
SOTO.CharacterTrait.CRUELTY2 = CharacterTrait.register("soto:cruelty2")
SOTO.CharacterTrait.PACIFIST2 = CharacterTrait.register("soto:pacifist2")
SOTO.CharacterTrait.ALCOHOLIC = CharacterTrait.register("soto:alcoholic")
SOTO.CharacterTrait.LESSSWEATY = CharacterTrait.register("soto:lesssweaty")
SOTO.CharacterTrait.HIGH_SWEATY = CharacterTrait.register("soto:highsweaty")
SOTO.CharacterTrait.ORGANIZED2 = CharacterTrait.register("soto:organized2")
SOTO.CharacterTrait.STRONG_BACK = CharacterTrait.register("soto:strongback")
SOTO.CharacterTrait.STRONG_BACK2 = CharacterTrait.register("soto:strongback2")
SOTO.CharacterTrait.WEAK_BACK = CharacterTrait.register("soto:weakback")
SOTO.CharacterTrait.DEXTROUS2 = CharacterTrait.register("soto:dextrous2")
SOTO.CharacterTrait.THICKBLOOD = CharacterTrait.register("soto:thickblood")
SOTO.CharacterTrait.LIQUIDBLOOD = CharacterTrait.register("soto:liquidblood")
SOTO.CharacterTrait.SENSITIVE_DIGESTION = CharacterTrait.register("soto:sensitivedigestion")
SOTO.CharacterTrait.LARKPERSON = CharacterTrait.register("soto:larkperson")
SOTO.CharacterTrait.OWLPERSON = CharacterTrait.register("soto:owlperson")
SOTO.CharacterTrait.OPTIMISTIC = CharacterTrait.register("soto:optimistic")
SOTO.CharacterTrait.DEPRESSIVE = CharacterTrait.register("soto:depressive")
SOTO.CharacterTrait.CHRONIC_MIGRAINE = CharacterTrait.register("soto:chronicmigraine")
SOTO.CharacterTrait.ALLERGIC = CharacterTrait.register("soto:allergic")
SOTO.CharacterTrait.PANIC_ATTACKS = CharacterTrait.register("soto:panicattacks")
SOTO.CharacterTrait.BREAK_IN_TECHNIQUE = CharacterTrait.register("soto:breakintechnique")
SOTO.CharacterTrait.USED_TO_CORPSES = CharacterTrait.register("soto:usedtocorpses")
SOTO.CharacterTrait.LIFELONG_LEARNER = CharacterTrait.register("soto:lifelonglearner")
SOTO.CharacterTrait.REFUELLER = CharacterTrait.register("soto:refueller")
SOTO.CharacterTrait.CUTTING_TOOLS = CharacterTrait.register("soto:cuttingtools")
SOTO.CharacterTrait.COMMERCIAL_DRIVER = CharacterTrait.register("soto:commercialdriver")
SOTO.CharacterTrait.FRAGILE_HEALTH = CharacterTrait.register("soto:fragilehealth")
--SOTO.CharacterTrait.SNORER = CharacterTrait.register("soto:snorer")	
SOTO.CharacterTrait.FORMER_ALCOHOLIC = CharacterTrait.register("soto:formeralcoholic")
SOTO.CharacterTrait.FORMER_SMOKER = CharacterTrait.register("soto:formersmoker")

-- =====================
-- CHARACTER PROFESSIONS
-- =====================

SOTO.CharacterProfession.DELIVERYMAN = CharacterProfession.register("soto:deliveryman")
SOTO.CharacterProfession.LOADER = CharacterProfession.register("soto:loader")
SOTO.CharacterProfession.TRUCK_DRIVER = CharacterProfession.register("soto:truckdriver")
SOTO.CharacterProfession.SOLDIER = CharacterProfession.register("soto:soldier")
SOTO.CharacterProfession.BOTANIST = CharacterProfession.register("soto:botanist")
SOTO.CharacterProfession.GRAVEDIGGER = CharacterProfession.register("soto:gravedigger")
SOTO.CharacterProfession.DANCER = CharacterProfession.register("soto:dancer")
SOTO.CharacterProfession.PRIEST = CharacterProfession.register("soto:priest")
SOTO.CharacterProfession.WEIGHTLIFTING_INSTRUCTOR = CharacterProfession.register("soto:weightliftinginstructor")
SOTO.CharacterProfession.DETECTIVE = CharacterProfession.register("soto:detective")
SOTO.CharacterProfession.SCHOOL_TEACHER = CharacterProfession.register("soto:schoolteacher")
SOTO.CharacterProfession.JANITOR = CharacterProfession.register("soto:janitor")
SOTO.CharacterProfession.STUNTMAN = CharacterProfession.register("soto:stuntman")
SOTO.CharacterProfession.GAS_STATION_OPERATOR = CharacterProfession.register("soto:gasstationoperator")
SOTO.CharacterProfession.CAMP_COUNSELOR = CharacterProfession.register("soto:campcounselor")
SOTO.CharacterProfession.DRAG_RACER = CharacterProfession.register("soto:dragracer")
SOTO.CharacterProfession.JUNKYARD_WORKER = CharacterProfession.register("soto:junkyardworker")
SOTO.CharacterProfession.LIFEGUARD = CharacterProfession.register("soto:lifeguard")
SOTO.CharacterProfession.DEMOLITION_WORKER = CharacterProfession.register("soto:demolitionworker")
SOTO.CharacterProfession.BUTCHER = CharacterProfession.register("soto:butcher")
SOTO.CharacterProfession.PAPARAZZI = CharacterProfession.register("soto:paparazzi")
SOTO.CharacterProfession.MINER = CharacterProfession.register("soto:miner")
SOTO.CharacterProfession.STORE_EMPLOYEE = CharacterProfession.register("soto:storeemployee")
SOTO.CharacterProfession.CRIMINAL = CharacterProfession.register("soto:criminal")
SOTO.CharacterProfession.ANIMAL_CONTROL_OFFICER = CharacterProfession.register("soto:animalcontrolofficer")
SOTO.CharacterProfession.HUNTSMAN = CharacterProfession.register("soto:huntsman")
SOTO.CharacterProfession.VETERINARIAN = CharacterProfession.register("soto:veterinarian")
	
	
--	CharacterTrait.WHITTLER:getName()
--	SOTO.CharacterTrait.WHITTLER:getName()

--   SOTO.CharacterProfession.SMITHER:getName()

--CharacterTrait.register("soto:enjoytheride")	
--CharacterTrait.register("soto:heavyaxemybeloved")
--CharacterTrait.register("soto:demostronggrip")
--CharacterTrait.register("soto:minersendurance")

